// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEqGX3ZmMYn6NJTZxdzu536W8cgaIX0Rk',
    appId: '1:735407955865:web:249bd3a56f4df934b1bd08',
    messagingSenderId: '735407955865',
    projectId: 'dine-now-fyp-a254d',
    authDomain: 'dine-now-fyp-a254d.firebaseapp.com',
    storageBucket: 'dine-now-fyp-a254d.firebasestorage.app',
    measurementId: 'G-GDY5NRRRY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH9AljURzwmCvbbcbw25XIrX4tkhqGV18',
    appId: '1:735407955865:android:6e33bdb83edd0199b1bd08',
    messagingSenderId: '735407955865',
    projectId: 'dine-now-fyp-a254d',
    storageBucket: 'dine-now-fyp-a254d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnbO2dtAmM5cFostAu6olHs_jh5abKjk',
    appId: '1:735407955865:ios:c685198d632949e8b1bd08',
    messagingSenderId: '735407955865',
    projectId: 'dine-now-fyp-a254d',
    storageBucket: 'dine-now-fyp-a254d.firebasestorage.app',
    iosBundleId: 'com.example.dineNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnbO2dtAmM5cFostAu6olHs_jh5abKjk',
    appId: '1:735407955865:ios:c685198d632949e8b1bd08',
    messagingSenderId: '735407955865',
    projectId: 'dine-now-fyp-a254d',
    storageBucket: 'dine-now-fyp-a254d.firebasestorage.app',
    iosBundleId: 'com.example.dineNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEqGX3ZmMYn6NJTZxdzu536W8cgaIX0Rk',
    appId: '1:735407955865:web:c23eb731c75ee2d9b1bd08',
    messagingSenderId: '735407955865',
    projectId: 'dine-now-fyp-a254d',
    authDomain: 'dine-now-fyp-a254d.firebaseapp.com',
    storageBucket: 'dine-now-fyp-a254d.firebasestorage.app',
    measurementId: 'G-KK0Y4E8WGG',
  );
}
